# Generated by Django 4.0.4 on 2022-05-29 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('order', '0004_auto_20220529_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='date_created',
            new_name='created',
        ),
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.CharField(default=False, max_length=250),
        ),
        migrations.AddField(
            model_name='payment',
            name='city',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='first_name',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_name',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
        ),
    ]
