# Generated by Django 4.0.4 on 2022-05-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentitem',
            old_name='order',
            new_name='payment',
        ),
    ]
